name: RELEASE

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Docs version to release'
  repository_dispatch:
    types: [release]

env:
  VERSION: $(if [ "${{ github.event.client_payload.version }}" != "" ]; then echo "${{ github.event.client_payload.version }}"; else echo "${{ github.event.inputs.version }}"; fi)

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  new-version:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          yarn 
          yarn build
      # https://docusaurus.io/docs/versioning#tagging-a-new-version
      - name: Tag version, commit the changes and push
        run: |
          echo ${{ env.VERSION }}
          yarn run docusaurus docs:version ${{ env.VERSION }}
          git add .
          git config --local user.email "iasql-bot@users.noreply.github.com"
          git config --local user.name "iasql-bot"
          git commit -m "${{ env.VERSION }}" -a
          git push