name: RELEASE

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    version:
      description: 'Docs version to release'
    inputs:
      version:
        required: false
        description: 'Version to update the docs to'
  repository_dispatch:
    types: [release]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  new-version:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          yarn 
          yarn build
      # https://docusaurus.io/docs/versioning#tagging-a-new-version
      - name: Tag a new version, commit the changes and push
        run: |
          export VERSION=(${{ github.event.client_payload.version }} ${{ github.event.client_payload.message.version }} ${{ github.event.inputs.version }})
          yarn run docusaurus docs:version $VERSION
          git config --local user.email "iasql-bot@users.noreply.github.com"
          git config --local user.name "iasql-bot"
          git commit -m "$VERSION" -a
          git push 